/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __eflcm_Frame_hpp__
#define __eflcm_Frame_hpp__

#include <vector>
#include <string>

namespace eflcm
{

class Frame
{
    public:
        int8_t     trackOnly;

        int8_t     compressed;

        int8_t     last;

        int32_t    depthSize;

        int32_t    imageSize;

        std::vector< uint8_t > depth;

        std::vector< uint8_t > image;

        int64_t    timestamp;

        int32_t    frameNumber;

        std::string senderName;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "Frame"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int Frame::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Frame::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Frame::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t Frame::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* Frame::getTypeName()
{
    return "Frame";
}

int Frame::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->trackOnly, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->compressed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->last, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->depthSize, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->imageSize, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->depthSize > 0) {
        tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->depth[0], this->depthSize);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->imageSize > 0) {
        tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->image[0], this->imageSize);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->frameNumber, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* senderName_cstr = (char*) this->senderName.c_str();
    tlen = __string_encode_array(buf, offset + pos, maxlen - pos, &senderName_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Frame::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->trackOnly, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->compressed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->last, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->depthSize, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->imageSize, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->depthSize) {
        this->depth.resize(this->depthSize);
        tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->depth[0], this->depthSize);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->imageSize) {
        this->image.resize(this->imageSize);
        tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->image[0], this->imageSize);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->frameNumber, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    int32_t __senderName_len__;
    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__senderName_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__senderName_len__ > maxlen - pos) return -1;
    this->senderName.assign(((const char*)buf) + offset + pos, __senderName_len__ - 1);
    pos += __senderName_len__;

    return pos;
}

int Frame::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->depthSize);
    enc_size += __byte_encoded_array_size(NULL, this->imageSize);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->senderName.size() + 4 + 1;
    return enc_size;
}

uint64_t Frame::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x4fb1058a78c4a44bLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
